---
title: "Statistical Learning"
author: "Ed Young"
date: "8/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(ISLR2)
```

# 2.4  Exercises

## Conceptual

1.  For each of parts (a) through (d), indicate whether we would generally expect the performance of a flexible statistical learning method to be better or worse than an inflexible method. Justify your answer.

    (a)The sample sizen is extremely large, and the number of predictors p is small.

    1.  (b)The number of predictors p is extremely large, and the number of observations n is small.

        (c)The relationship between the predictors and response is highly non-linear.

        (d)The variance of the error terms, i.e.σ^2^= Var(ε), is extremely high.

2.  Explain whether each scenario is a classification or regression problem, and indicate whether we are most interested in inference or prediction. Finally, provide n and p.

    (a) We collect a set of data on the top 500 firms in the US. For eachfirm we record profit, number of employees, industry and theCEO salary. We are interested in understanding which factorsaffect CEO salary.

    (b) We are considering launching a new product and wish to knowwhether it will be asuccessor afailure. We collect data on 20similar products that were previously launched. For each prod-uct we have recorded whether it was a success or failure, pricecharged for the product, marketing budget, competition price,and ten other variables.

    (c) We are interested in predicting the % change in the USD/Euroexchange rate in relation to the weekly changes in the worldstock markets. Hence we collect weekly data for all of 2012. Foreach week we record the % change in the USD/Euro, the %change in the US market, the % change in the British market,and the % change in the German market.

3.  We now revisit the bias-variance decomposition

    (a) Provide a sketch of typical (squared) bias, variance, training error, test error, and Bayes (or irreducible) error curves, on a single plot, as we go from less flexible statistical learning methods towards more flexible approaches. The x-axis should represent the amount of flexibility in the method, and the y-axis should represent the values for each curve. There should be five curves. Make sure to label each one

    (b) Explain why each of the five curves has the shape displayed inpart (a).

4.  You will now think of some real-life applications for statistical learning.

    (a)Describe three real-life applications in which classification might be useful. Describe the response, as well as the predictors. Is the goal of each application inference or prediction? Explain your answer.

    (b) Describe three real-life applications in which regression might be useful. Describe the response, as well as the predictors. Is the goal of each application inference or prediction? Explain your answer

    (c) Describe three real-life applications in which cluster analysis might be useful.

5.  What are the advantages and disadvantages of a very flexible (versusa less flexible) approach for regression or classification? Under what circumstances might a more flexible approach be preferred to a less flexible approach? When might a less flexible approach be preferred?

6.  Describe the differences between a parametric and a non-parametricstatistical learning approach. What are the advantages of a para-metric approach to regression or classification (as opposed to a non-parametric approach)? What are its disadvantages?

7.  The table below provides a training data set containing six observa-tions, three predictors, and one qualitative response variable.

| Obs | X~1~ | X~2~ | X~3~ | X~4~  |
|-----|------|------|------|-------|
| 1   | 0    | 3    | 0    | Red   |
| 2   | 2    | 0    | 0    | Red   |
| 3   | 0    | 1    | 3    | Red   |
| 4   | 0    | 1    | 2    | Green |
| 5   | -1   | 0    | 1    | Green |
| 6   | 1    | 1    | 1    | Red   |
|     |      |      |      |       |

Suppose we wish to use this data set to make a prediction forYwhenX1=X2=X3= 0 usingK-nearest neighbors.(a)Compute the Euclidean distance between each observation andthe test point,X1=X2=X3= 0.(b)What is our prediction withK= 1? Why?(c)What is our prediction withK= 3? Why?(d)If the Bayes decision boundary in this problem is highly non-linear, then would we expect thebestvalue forKto be large orsmall? Why?
